***Matrix-Vector Dot Product***

In [1]:
# using numpy 

import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1. 
	a = np.array(a)
	b = np.array(b)
	if a.shape[1] != b.shape[0]:          # a.shape[0] → number of rows   ||   a.shape[1] → number of columns
		return -1
	return (a @ b).tolist()	

matrix_dot_vector(a = [[1, 2], [2, 4]], b = [1, 2])

[5, 10]

In [2]:
# Using Python 

def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
    
    result = []

    for row in a :  # first iteration : row = [1, 2]
        sum_ = 0 
        if len(a) != len(b):
            return -1
        for row_element , vector_element in zip(row , b):   # row = [1, 2], b = [1, 2]  || zip(row, b) → [(1,1), (2,2)]
            sum_ += row_element * vector_element 
        result.append(sum_)    
    return result    
        
matrix_dot_vector(a = [[1, 2], [2, 4]], b = [1, 2])

[5, 10]

***Transpose of a Matrix***

In [3]:
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    """
    Transpose a 2D matrix by swapping rows and columns.
    
    Args:
        a: A 2D matrix of shape (m, n)
    
    Returns:
        The transposed matrix of shape (n, m)
    """
    # Your code here
    m , n = len(a) , len(a[0])
    transposed_a = [[0] * m for _  in range(n)]
    for i in range(n):
        for j in range(m):
            transposed_a[i][j] = a[j][i]
    return transposed_a        

    # one line of code 
    # return [ list(row) for row in zip(*a) ]      

transpose_matrix(a = [[1, 2, 3], [4, 5, 6]])

[[1, 4], [2, 5], [3, 6]]

In [4]:
# Using Numpy 
import numpy as np

def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    a = np.array(a)
    return (a.T).tolist()

transpose_matrix(a = [[1, 2, 3], [4, 5, 6]])
    


[[1, 4], [2, 5], [3, 6]]

***Dot Product Calculator***

In [5]:
import numpy as np

def calculate_dot_product(vec1, vec2):
	"""
	Calculate the dot product of two vectors.
	Args:
		vec1 (numpy.ndarray): 1D array representing the first vector.
		vec2 (numpy.ndarray): 1D array representing the second vector.
	Returns:
		The dot product of the two vectors.
	"""
	# Your code here
	vec1 = np.array(vec1)
	vec2 = np.array(vec2)
	return (vec1 @ vec2).tolist()

***Scalar Multiplication of a Matrix***

In [6]:
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	result = []
	for row in matrix:
		new_row = []
		for elemnt in row:
			new_row.append(elemnt * scalar)
		result.append(new_row)
	return result		

scalar_multiply(matrix = [[1, 2], [3, 4]], scalar = 2)

[[2, 4], [6, 8]]

***Reshape Matrix***

In [7]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
	a = np.array(a)
	p_old , q_old = len(a) , len(a[0])
	p_new , q_new = new_shape[0] , new_shape[1]
	if p_old * q_old != p_new * q_new:
		return []
	else:
		return a.reshape(p_new,q_new).tolist()



***Calculate Mean by Row or Column***

In [8]:
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
	n_columns = len(matrix[0])
	means = []
	if mode == 'row':
		for row in matrix:
			mean = sum(row) / len(row)
			means.append(mean)
	else:
		for i in range(n_columns):
			column = [row[i] for row in matrix]
			mean = sum(column) / len(column)
			means.append(mean)		
	return means

calculate_matrix_mean(matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], mode = 'column')

[4.0, 5.0, 6.0]

In [9]:
# Using Numpy 

import numpy as np 

def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
    
    matrix = np.array(matrix)

    if mode == 'row':
        means = matrix.mean(axis = 1)
    else:
        means = matrix.mean(axis = 0)
    return means.tolist()       

calculate_matrix_mean(matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], mode = 'column')


[4.0, 5.0, 6.0]

***Calculate Cosine Similarity Between Vectors***

Cosine Similarity explains how similar two vectors are in terms of direction.
The result is always between -1 and 1:
   1.0  → vectors point in the same direction (perfect similarity)
  0.0  → vectors are perpendicular (no similarity)
 -1.0  → vectors point in opposite directions

How it works step by step:
 Step 1 - Validate inputs:
   - Convert both inputs to numpy arrays
   - Check if either vector is empty
   - Check if both vectors have the same shape

Step 2 - Dot Product (numerator):
   - Multiply each pair of corresponding elements together
   - Example: v1=[1,2,3] v2=[2,4,6] → (1×2) + (2×4) + (3×6) = 28

Step 3 - Magnitude (denominator):
   - Calculate the length of each vector using np.linalg.norm()
   - Which is the square root of the sum of squared elements
   - Then multiply both magnitudes together

Step 4 - Divide:
   - dot_product / (magnitude_v1 * magnitude_v2)
   - This gives the cosine of the angle between the two vectors

In [10]:
import numpy as np

def cosine_similarity(v1, v2):
    v1 = np.array(v1)
    v2 = np.array(v2)
    
    if len(v1) == 0 or len(v2) == 0:
        raise ValueError("Vectors cannot be empty")
    if v1.shape != v2.shape:
        raise ValueError("Vectors must have the same shape")
    
    dot_product = np.dot(v1, v2)
    magnitude = np.linalg.norm(v1) * np.linalg.norm(v2)
    
    return dot_product / magnitude
	
    
v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 6])
print(round(cosine_similarity(v1, v2), 3))	
	

1.0


***Matrix Transformation***

In [12]:
import numpy as np

def transform_matrix(A: list[list[int|float]], T: list[list[int|float]], S: list[list[int|float]]) -> list[list[int|float]]:
    A , T , S = np.array(A) , np.array(T) , np.array(S)
    def is_invertable(X):
        m , n = X.shape
        if m != n or np.linalg.det(X) == 0.0:
            return False 
        return True
    if not is_invertable(S) or not is_invertable(T):
        return -1 
    transform_matrix = np.linalg.inv(T) @ A @ S

    return transform_matrix
	


print(transform_matrix([[1, 2], [3, 4]], [[2, 0], [0, 2]], [[1, 1], [0, 1]]))    

[[0.5 1.5]
 [1.5 3.5]]


***Calculate 2x2 Matrix Inverse***

In [5]:
def inverse_2x2(matrix: list[list[float]]) -> list[list[float]] | None:
    """
    Calculate the inverse of a 2x2 matrix.
    
    Args:
        matrix: A 2x2 matrix represented as [[a, b], [c, d]]
    
    Returns:
        The inverse matrix as a 2x2 list, or None if the matrix is singular
        (i.e., determinant equals zero)
    """
    # Your code here
    # so first extract a,b,c,d : remember that matrix is list of list 
    a , b , c , d  = matrix[0][0] , matrix[0][1] , matrix[1][0] , matrix[1][1]
    det = a * d - b * c
    if det == 0:
        return None
    
    # So each element gets multiplied by 1/det, and a and d swap, while b and c get negated.

    return [[d/det, -b/det], [-c/det, a/det]]
     # return [[(1/det) * d,  (1/det) * -b] , [(1/det) * -c, (1/det) * a]]


print(inverse_2x2([[4, 7], [2, 6]]))

[[0.6, -0.7], [-0.2, 0.4]]


In [8]:
import numpy as np

def inverse_2x2_numpy(matrix):
    m = np.array(matrix)
    # np.linalg.det() → computes the determinant
    det = np.linalg.det(m)
    if det == 0:
        return None
    # np.linalg.inv() → computes the inverse directly
    return np.linalg.inv(m).tolist()

print(inverse_2x2([[4, 7], [2, 6]]))

[[0.6, -0.7], [-0.2, 0.4]]


***Calculate Eigenvalues of a Matrix***

In [12]:
import math
def calculate_eigenvalues(matrix: list[list[float|int]]) -> list[float]:
	
	a , b , c , d  = matrix[0][0] , matrix[0][1] , matrix[1][0] , matrix[1][1]
	det = a * d - b * c
	trace = a + d
	lambda1 = (trace + math.sqrt(trace**2 - 4*det)) / 2
	lambda2 = (trace - math.sqrt(trace**2 - 4*det)) / 2
 
	return sorted([lambda1, lambda2], reverse=True)

print(calculate_eigenvalues([[2, 1], [1, 2]]))
	

[3.0, 1.0]


In [ ]:

import numpy as np 
def calculate_eigenvalues(matrix: list[list[float|int]]) -> list[float]:
	matrix = np.array(matrix)
	eigenvalues = np.linalg.eigvals(matrix)
	return [float(v) for v in sorted(eigenvalues, reverse=True)]
 
print(calculate_eigenvalues([[2, 1], [1, 2]]))
	

[3.0, 1.0]


***Convert Vector to Diagonal Matrix***

In [2]:
import numpy as np

def make_diagonal(x):
	# Your code here
	x = np.array(x)
	result = np.diag(x)
	return result

output = make_diagonal([1, 2, 3])
print(output)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [10]:
def make_diagonal(x):
    # size of the list
    n = len(x)
    new_x = [[0] * n for _ in range(n)]
     # new_x[0][0] , new_x[1][1] , new_x[2][2]= x[0] , x[1] , x[2] # this it will work only if we have 3 element 
    for i in range (n):
        new_x[i][i] = x[i]
    return new_x

make_diagonal([1, 2, 3])

[[1, 0, 0], [0, 2, 0], [0, 0, 3]]

***Matrix times Matrix***

In [12]:
def matrixmul(a:list[list[int|float]],b:list[list[int|float]])-> list[list[int|float]]:
	# Two matrices align for multiplication when: 
        # The number of columns in matrix A equals the number of rows in matrix B
    if len(a[0]) != len(b):
        return -1
    rows = len(a)
    cols = len(b[0])
    c = [[0] * cols for _ in range(rows)]
     
    for i in range(len(a)):        # rows of A
        for j in range(len(b[0])): # columns of B
            for k in range(len(b)): # accumulate
                c[i][j] += a[i][k] * b[k][j]

    return c

print(matrixmul([[1,2,3],[2,3,4],[5,6,7]],[[3,2,1],[4,3,2],[5,4,3]]))


[[26, 20, 14], [38, 29, 20], [74, 56, 38]]


***Calculate Covariance Matrix***

In [14]:
def calculate_covariance_matrix(vectors: list[list[float]]) -> list[list[float]]:
	# Your code here
	f1 , f2 = vectors[0] , vectors[1]
	mean1 = sum(f1) / len(f1)
	mean2 = sum(f2) / len(f2)
	cove_f1_f2 = sum(((f1[i]-mean1) * (f2[i]-mean2))  for i in range(len(f1))) / (len(f1)-1)
	cov_f1_f1 = sum(((f1[i]-mean1)**2)  for i in range(len(f1))) / (len(f1)-1)
	cov_f2_f2  = sum(((f2[i]-mean2)**2)  for i in range(len(f1))) / (len(f1)-1)
	# cov(f2,f1) == cov(f1,f2)
	cov_f2_f1 = cove_f1_f2
	
	return [[cov_f1_f1,cove_f1_f2],[cov_f2_f1,cov_f2_f2]]
    

print(calculate_covariance_matrix([[1, 2, 3], [4, 5, 6]]))    
	

[[1.0, 1.0], [1.0, 1.0]]


In [16]:
def calculate_covariance_matrix(vectors: list[list[float]]) -> list[list[float]]:
    n = len(vectors)        # number of features
    m = len(vectors[0])     # number of observations
    
    # step 1: calculate mean for each feature
    means = [sum(v) / len(v) for v in vectors]
    
    # step 2: initialize n x n matrix of zeros
    cov_matrix = [[0]*n for _ in range(n)]
    
    # step 3: nested loop over each pair (i, j)
    for i in range(n):
        for j in range(n):
            cov_matrix[i][j] = sum((vectors[i][k] - means[i]) * (vectors[j][k] - means[j]) for k in range(m)) / (m - 1)
    
    return cov_matrix

print(calculate_covariance_matrix([[1, 2, 3], [4, 5, 6]]))

[[1.0, 1.0], [1.0, 1.0]]


***Find the Image of a Matrix Using Row Echelon Form***

In [ ]:
import numpy as np

def matrix_image(A):
    A = A.astype(float)          # work with floats
    m, n = A.shape
    R = A.copy()

    pivot_cols = []
    row = 0

    for col in range(n):
        # Find a pivot row
        pivot = None
        for r in range(row, m):
            if abs(R[r, col]) > 1e-10:
                pivot = r
                break

        if pivot is None:
            continue

        # Swap rows
        R[[row, pivot]] = R[[pivot, row]]

        # Eliminate below
        for r in range(row + 1, m):
            R[r] -= (R[r, col] / R[row, col]) * R[row]

        pivot_cols.append(col)
        row += 1

        if row == m:
            break

    # Extract independent columns from ORIGINAL matrix
    return A[:, pivot_cols].astype(int)


import numpy as np

def matrix_image(A):
    A = A.astype(float)          # work with floats
    m, n = A.shape
    R = A.copy()

    pivot_cols = []
    row = 0

    for col in range(n):
        # Find a pivot row
        pivot = None
        for r in range(row, m):
            if abs(R[r, col]) > 1e-10:
                pivot = r
                break

        if pivot is None:
            continue

        # Swap rows
        R[[row, pivot]] = R[[pivot, row]]

        # Eliminate below
        for r in range(row + 1, m):
            R[r] -= (R[r, col] / R[row, col]) * R[row]

        pivot_cols.append(col)
        row += 1

        if row == m:
            break

    # Extract independent columns from ORIGINAL matrix
    return A[:, pivot_cols].astype(int)


import numpy as np

def matrix_image(A):
    A = A.astype(float)          # work with floats
    m, n = A.shape
    R = A.copy()

    pivot_cols = []
    row = 0

    for col in range(n):
        # Find a pivot row
        pivot = None
        for r in range(row, m):
            if abs(R[r, col]) > 1e-10:
                pivot = r
                break

        if pivot is None:
            continue

        # Swap rows
        R[[row, pivot]] = R[[pivot, row]]

        # Eliminate below
        for r in range(row + 1, m):
            R[r] -= (R[r, col] / R[row, col]) * R[row]

        pivot_cols.append(col)
        row += 1

        if row == m:
            break

    # Extract independent columns from ORIGINAL matrix
    return A[:, pivot_cols].astype(int)


matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix_image(matrix))


[[1 2]
 [4 5]
 [7 8]]


***Poisson Distribution Probability Calculator***

In [1]:
import math

def poisson_probability(k, lam):
	"""
	Calculate the probability of observing exactly k events in a fixed interval,
	given the mean rate of events lam, using the Poisson distribution formula.
	:param k: Number of events (non-negative integer)
	:param lam: The average rate (mean) of occurrences in a fixed interval
	"""
	# Your code here
	# val = (math.exp(-lam) * lam ** k) / math.factorial(k)
	val = (math.pow(lam,k) * math.exp(-lam) ) / math.factorial(k)
	return round(val,5)

print(poisson_probability(3, 5))

0.14037


***Binomial Distribution Probability***

In [6]:
import math

def binomial_probability(n: int, k: int, p: float) -> float:
    """
    Calculate the probability of exactly k successes in n Bernoulli trials.
    
    Args:
        n: Total number of trials
        k: Number of successes
        p: Probability of success on each trial
    
    Returns:
        Probability of k successes
    """
    # Your code here
    binomal_coeff = math.factorial(n) / (math.factorial(k) * math.factorial(n-k))
    Success_term = math.pow(p,k)
    Failure_term = math.pow((1-p),(n-k))
    Result =  binomal_coeff * Success_term * Failure_term 
    return Result

print(round(binomial_probability(6, 2, 0.5), 5))



0.23438


***Normal Distribution PDF Calculator***


In [6]:
import math

def normal_pdf(x, mean, std_dev):
	"""
	Calculate the probability density function (PDF) of the normal distribution.
	:param x: The value at which the PDF is evaluated.
	:param mean: The mean (μ) of the distribution.
	:param std_dev: The standard deviation (σ) of the distribution.
	"""
	# Your code here
	
	val = (1 / (math.sqrt(2 * math.pi * std_dev **2)))  * math.exp(-(x-mean)**2 / (2 * std_dev **2))
		
	return round(val,5)

print(normal_pdf(0, 0, 1))
print(normal_pdf(16, 15, 2.04))
print(normal_pdf(1, 0, 0.5))

0.39894
0.17342
0.10798


In [8]:
import math

def normal_pdf(x, mean, std_dev):
	"""
	Calculate the probability density function (PDF) of the normal distribution.
	:param x: The value at which the PDF is evaluated.
	:param mean: The mean (μ) of the distribution.
	:param std_dev: The standard deviation (σ) of the distribution.
	"""
	# Your code here
	# mean = sum(x) / len(x)
	# std_dev = math.sqrt(sum((i - mean)**2 for i in x) / len(x))
	
	val = (1 / (math.sqrt(2 * math.pi * std_dev **2)))  * math.exp(-(x-mean)**2 / (2 * std_dev **2))
		
	return round(val,5)

print(normal_pdf(0, 0, 1))
print(normal_pdf(16, 15, 2.04))
print(normal_pdf(1, 0, 0.5))

0.39894
0.17342
0.10798


***Descriptive Statistics Calculator***

In [16]:
import numpy as np
from collections import Counter

def descriptive_statistics(data: list | np.ndarray) -> dict:
    """
    Calculate various descriptive statistics metrics for a given dataset.
    
    Args:
        data: List or numpy array of numerical values
    
    Returns:
        Dictionary containing mean, median, mode, variance, standard deviation,
        percentiles (25th, 50th, 75th), and interquartile range (IQR)
    """
    # Your code here
    count = Counter(data).most_common(1)
    mean  = np.mean(data)
    median = np.median(data)
    mode = count[0][0]
    variance = np.var(data)
    std_dev = np.std(data)
    per_25 = np.percentile(data,25)
    per_50 = np.percentile(data,50)
    per_75 = np.percentile(data,75)
    interquartile_range = per_75 - per_25

    return {
    'mean': round(float(mean), 4),
    'median': round(float(median), 4),
    'mode': mode,
    'variance': round(float(variance), 4),
    'standard_deviation': round(float(std_dev), 4),
    '25th_percentile': round(float(per_25), 4),
    '50th_percentile': round(float(per_50), 4),
    '75th_percentile': round(float(per_75), 4),
    'interquartile_range': round(float(interquartile_range), 4)
}


result = descriptive_statistics([1, 2, 2, 3, 4, 4, 4, 5])
print({k: round(v, 4) if isinstance(v, float) else v for k, v in result.items()})

{'mean': 3.125, 'median': 3.5, 'mode': 4, 'variance': 1.6094, 'standard_deviation': 1.2686, '25th_percentile': 2.0, '50th_percentile': 3.5, '75th_percentile': 4.0, 'interquartile_range': 2.0}


***Calculate the Phi Coefficient***

In [2]:
def phi_corr(x: list[int], y: list[int]) -> float:
    x00 = 0
    x01 = 0
    x10 = 0
    x11 = 0
    for xi, yi in zip(x, y):
        if xi == 0 and yi == 0:
            x00 += 1
        elif xi == 0 and yi == 1:
            x01 += 1
        elif xi == 1 and yi == 0:
            x10 += 1
        else:
            x11 += 1
    val = ((x00 * x11) - (x01 * x10)) / ((x00+x01)*(x10+x11)*(x00+x10)*(x01+x11)) ** 0.5
    return round(val, 4)

print(phi_corr([1, 1, 0, 0], [0, 0, 1, 1]))

-1.0


***Gradient Direction and Magnitude***


In [ ]:
import numpy as np

def gradient_direction_magnitude(gradient: list) -> dict:
	"""
	Calculate the magnitude and direction of a gradient vector.
	
	Args:
		gradient: A list representing the gradient vector
	
	Returns:
		Dictionary containing:
		- magnitude: The L2 norm of the gradient
		- direction: Unit vector in direction of steepest ascent
		- descent_direction: Unit vector in direction of steepest descent
	"""
	# Your code here
	gradient = np.array(gradient)
	Magnitude = np.linalg.norm(gradient)
	if Magnitude == 0 :
		Magnitude = None
	Direction = gradient / Magnitude
	Descent_direction = -Direction
	return {'magnitude': Magnitude, 'direction': Direction.tolist(), 'descent_direction': Descent_direction.tolist()}

result = gradient_direction_magnitude([3.0, 4.0])
print(f"{result['magnitude']:.4f},{[round(d,4) for d in result['direction']]},{[round(d,4) for d in result['descent_direction']]}")

5.0000,[0.6, 0.8],[-0.6, -0.8]


***Product Rule for Derivatives***

In [11]:
import numpy as np
def product_rule_derivative(f_coeffs, g_coeffs):
    def poly_derivative(coeffs):
        return [i * coeffs[i] for i in range(1, len(coeffs))]
    
    f_prime = poly_derivative(f_coeffs)
    g_prime = poly_derivative(g_coeffs)
    
    f_prime_g = np.convolve(f_prime, g_coeffs)
    f_g_prime = np.convolve(f_coeffs, g_prime)
    
    # Add the two results (hint: np.polyadd handles different lengths!)
    result = np.polyadd(f_prime_g,f_g_prime)
    
    # Round to 4 decimal places and convert to list
    result = [round(float(c), 4) for c in result]
    
    # Remove trailing zeros (but return [0.0] if all zeros)
    while len(result) > 1 and result[-1] == 0.0:
        result.pop()
    
    return result

print(product_rule_derivative([1, 2], [3, 4]))

[10.0, 16.0]


***Linear Regression Using Normal Equation***

In [7]:
import numpy as np
def linear_regression_normal_equation(X: list[list[float]], y: list[float]) -> list[float]:
    X , y = np.array(X) , np.array(y)

    theta = np.linalg.inv(X.T @ X) @ X.T @ y

    return np.round(theta, 4).tolist()

print(linear_regression_normal_equation(X = [[1, 1], [1, 2], [1, 3]], y = [1, 2, 3]))

[-0.0, 1.0]


***Linear Regression Using Gradient Descent***

In [ ]:
import numpy as np

def linear_regression_gradient_descent(X: np.ndarray, y: np.ndarray, alpha: float, iterations: int) -> np.ndarray:
    """
    Perform linear regression using gradient descent.

    Args:
        X: Feature matrix of shape (m, n) where first column is all ones (for intercept)
        y: Target vector of shape (m,)
        alpha: Learning rate
        iterations: Number of gradient descent iterations
    
    Returns:
        Learned weights as a 1D array of shape (n,)
    """
    m, n = X.shape
    y = y.reshape(-1, 1)  # Ensure y is a column vector
    theta = np.zeros((n, 1))  # Initialize weights to zeros
    y = y[:None]
    for interation in range(iterations):
        gradient = (1/m) * X.T @ (X @ theta -y)
        theta = theta - alpha * gradient
    # Your code here: implement gradient descent
    
    return theta.flatten()

In [ ]:
import numpy as np
import math
def calculate_latency_percentiles(latencies: list[float]) -> dict[str, float]:
    """
    Calculate P50, P95, and P99 latency percentiles.
    
    Args:
        latencies: List of latency measurements
    
    Returns:
        Dictionary with keys 'P50', 'P95', 'P99' containing
        the respective percentile values rounded to 4 decimal places
    """
    # Your code here
    if not latencies :
        return {'P50': 0.0, 'P95': 0.0, 'P99': 0.0}
    latencies = sorted(latencies)
    n = len(latencies)
    position_50 = (50 / 100) * (n - 1)
    fraction_50 = position_50 - math.floor(position_50)
    P50 = latencies[math.floor(position_50)] + fraction_50 * (latencies[math.ceil(position_50)] - latencies[math.floor(position_50)]) 
    position_95 = (95 / 100) * (n - 1)
    fraction_95 = position_95 - math.floor(position_95)
    P95 = latencies[math.floor(position_95)] + fraction_95 * (latencies[math.ceil(position_95)] - latencies[math.floor(position_95)]) 
    position_99 = (99 / 100) * (n - 1)
    fraction_99 = position_99 - math.floor(position_99)
    P99 = latencies[math.floor(position_99)] + fraction_99 * (latencies[math.ceil(position_99)] - latencies[math.floor(position_99)])

    return {'P50': round(P50,1), 'P95': round(P95,1), 'P99': round(P99,1)}

print(calculate_latency_percentiles([10, 20, 30, 40, 50, 60, 70, 80, 90, 100]))

{'P50': 55.0, 'P95': 95, 'P99': 99}


***Feature Scaling Implementation***

In [5]:
import numpy as np 
def feature_scaling(data: np.ndarray) :
	# Your code here
	standardized_data = (data - data.mean(axis=0)) / (data.std(axis=0)) 
	normalized_data = (data - data.min(axis = 0)) / ((data.max(axis=0) - data.min(axis=0)))
	return np.round(standardized_data,4).tolist(), np.round(normalized_data,4).tolist()

print(feature_scaling(np.array([[1, 2], [3, 4], [5, 6]])))

([[-1.2247, -1.2247], [0.0, 0.0], [1.2247, 1.2247]], [[0.0, 0.0], [0.5, 0.5], [1.0, 1.0]])


***Random Shuffle of Dataset***

In [1]:
import numpy as np

def shuffle_data(X, y, seed=None):
	# Your code here
	if seed is not None:
		np.random.seed(seed)
		
	arr = np.arange(0 , len(X))    
	np.random.shuffle(arr)
	return X[arr] , y[arr]
        
print(shuffle_data(np.array([[1, 2], [3, 4], [5, 6], [7, 8]]), np.array([1, 2, 3, 4]), seed=42))

(array([[3, 4],
       [7, 8],
       [1, 2],
       [5, 6]]), array([2, 4, 1, 3]))


***Vector Element-wise Sum***

In [ ]:
def vector_sum(a: list[int|float], b: list[int|float]) -> list[int|float]:
	# Return the element-wise sum of vectors 'a' and 'b'.
	# If vectors have different lengths, return -1.
	q , p = len(a) , len(b)
	if q != p :
		return -1
	else :
		return [a + b for a , b in zip(a,b)] 

***Compute the Cross Product of Two 3D Vectors***

In [3]:
import numpy as np

def cross_product(a, b):
    # Your code here
    return [a[1]*b[2] - a[2]*b[1],a[2]*b[0] - a[0]*b[2],a[0]*b[1] - a[1]*b[0]]
    # using numpy
    # np.cross(a, b).tolist()

***Implement Gradient Descent Variants with MSE Loss***

In [3]:
import numpy as np

def gradient_descent(X, y, weights, learning_rate, n_epochs, batch_size=1, method='batch'):
    """
    Perform gradient descent optimization.
    
    Args:
        X: Feature matrix of shape (m, n)
        y: Target values of shape (m,)
        weights: Initial weights of shape (n,)
        learning_rate: Step size for gradient descent
        n_epochs: Number of complete passes through the dataset
        batch_size: Size of batches for mini-batch gradient descent (default: 1)
        method: Type of gradient descent ('batch', 'stochastic', or 'mini_batch')
    
    Returns:
        Optimized weights
    """
    # Your code here
    X = np.array(X)
    y = np.array(y)
    for _ in range(n_epochs):
        if method == 'batch':
            prediction = X @ weights
            error = prediction - y
            gradient = 2 * X.T @ error / len(X)
            weights = weights - learning_rate * gradient
        elif method == 'stochastic':
            for i in range(len(X)):
                X_sample = X[i:i+1]  # shape (1, n)
                y_sample = y[i:i+1]  # shape (1,)
                prediction = X_sample @ weights
                error = prediction - y_sample
                gradient = 2 * X_sample.T @ error 
                weights = weights - learning_rate * gradient
        elif method == 'mini_batch':
            for i in range(0, len(X), batch_size):
                X_batch = X[i : i + batch_size]
                y_batch = y[i : i + batch_size]   
                prediction = X_batch @ weights
                error = prediction - y_batch
                gradient = 2 * X_batch.T @ error / batch_size
                weights = weights - learning_rate * gradient

    return weights        



X = np.array([[1, 1], [2, 1], [3, 1], [4, 1]])
y = np.array([2, 3, 4, 5])
weights = np.zeros(X.shape[1])
learning_rate = 0.01
n_epochs = 100

# Test Batch Gradient Descent
output = gradient_descent(X, y, weights, learning_rate, n_epochs, method='batch')
print(output)

[1.14905239 0.56176776]


***Calculate Mean Absolute Error (MAE)***

In [ ]:
import numpy as np

def mae(y_true, y_pred):
    """
    Calculate Mean Absolute Error between two arrays.

    Parameters:
        y_true (numpy.ndarray): Array of true values
        y_pred (numpy.ndarray): Array of predicted values

    Returns:
        float: Mean Absolute Error
    """
    # Your code here
    
    MAE = np.mean(np.abs(y_true - y_pred))
    return np.round(MAE , 3 )

print(np.round(mae(np.array([3, -0.5, 2, 7]), np.array([2.5, 0.0, 2, 8])), 3))
print(round(mae(np.array([[0.5, 1], [-1, 1], [7, -6]]), np.array([[0, 2], [-1, 2], [8, -5]])), 3))

0.5
0.75


***One-Hot Encoding of Nominal Values***

In [19]:
import numpy as np

def to_categorical(x, n_col=None):
	# Your code here
	if not n_col :
		n_col = len(np.unique(x))
		
	output = np.zeros((len(x), n_col))
	for row , column  in enumerate(x):
		output[row][column] = 1
		
	return output 
print(to_categorical(np.array([0, 1, 2, 1, 0])))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


***Calculate Accuracy Score***

In [16]:
import numpy as np

def accuracy_score(y_true, y_pred):
	# Your code here
	# Accuracy = (TP + TN) / (TP + TN + FP + FN)
	n = len(y_true)
	# return np.sum(y_true == y_pred) / n 
	return np.mean(y_true==y_pred)
    

y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 0, 1, 0, 1])
output = accuracy_score(y_true, y_pred)
print(output)		

0.8333333333333334


***Chain Rule for Composite Functions***

In [22]:
import numpy as np

def compute_chain_rule_gradient(functions: list[str], x: float) -> float:
	"""
	Compute derivative of composite functions using chain rule.
	
	Args:
		functions: List of function names (applied right to left)
		          Available: 'square', 'sin', 'exp', 'log'
		x: Point at which to evaluate derivative
	
	Returns:
		Derivative value at x
	
	Example:
		['sin', 'square'] represents sin(x²)
		['exp', 'sin', 'square'] represents exp(sin(x²))
	"""
	# Your code here
	# Forward pass 
	derivs = {
    'square': lambda x: 2*x,
    'sin': np.cos,
    'exp': np.exp,
    'log': lambda x: 1/x,
}
	funcs = {
    'square': lambda x: x**2,
    'sin': np.sin,
    'exp': np.exp,
    'log': np.log,
}
	u = x
	intermediates = [x]
	for f in reversed(functions):
		u = funcs[f](u)
		intermediates.append(u)
    
    # back pass 
	result = 1.0
	for i , f in enumerate(reversed(functions)):
		result *= derivs[f](intermediates[i])
	return round(result , 6)
		
result = compute_chain_rule_gradient(['sin', 'square'], 1.0); print(f"{result:.6f}")        
		
       

	

1.080605


***Transformation Matrix from Basis B to C***

In [9]:
import numpy as np 
def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:
	# P=C −1⋅B
	B = np.array(B)
	C = np.array(C)
	P = np.linalg.inv(C) @ B
	return np.round(P , 4).tolist()

print(transform_basis([[1, 0, 0], [0, 1, 0], [0, 0, 1]], [[1, 2.3, 3], [4.4, 25, 6], [7.4, 8, 9]]))

[[-0.6772, -0.0126, 0.2342], [-0.0184, 0.0505, -0.0275], [0.5732, -0.0345, -0.0569]]


***Calculate R-squared for Regression Analysis***

In [2]:

import numpy as np

def r_squared(y_true, y_pred):
	# Write your code here
	ssr = np.sum((y_true - y_pred)**2)
	sst = np.sum((y_true - np.mean(y_pred))**2)
	R_squared = 1 - (ssr / sst)
	return np.round(R_squared , 4)

y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1.1, 2.1, 2.9, 4.2, 4.8])
print(r_squared(y_true, y_pred))


0.989


***Calculate Mean Absolute Error (MAE)***

In [7]:
import numpy as np

def mae(y_true, y_pred):
    """
    Calculate Mean Absolute Error between two arrays.

    Parameters:
        y_true (numpy.ndarray): Array of true values
        y_pred (numpy.ndarray): Array of predicted values

    Returns:
        float: Mean Absolute Error
    """
    # Your code here
    
    MAE = np.mean(np.abs(y_true - y_pred))
    return np.round(MAE , 3 )

print(np.round(mae(np.array([3, -0.5, 2, 7]), np.array([2.5, 0.0, 2, 8])), 3))

0.5


***Calculate Root Mean Square Error (RMSE)***

In [10]:

import numpy as np

def rmse(y_true, y_pred):
	# Write your code here
	rmse_res = np.sqrt(np.mean((y_true - y_pred)**2))
	return round(rmse_res,3)

# Test Case 1: Normal Case  
y_true1 = np.array([3, -0.5, 2, 7])
y_pred1 = np.array([2.5, 0.0, 2, 8])
print(rmse(y_true1, y_pred1))

0.612


***Implement F-Score Calculation for Binary Classification***

In [1]:
import numpy as np

def f_score(y_true, y_pred, beta):
	"""
	Calculate F-Score for a binary classification task.

	:param y_true: Numpy array of true labels
	:param y_pred: Numpy array of predicted labels
	:param beta: The weight of precision in the harmonic mean
	:return: F-Score rounded to three decimal places
	"""
	TP = np.sum((y_true == 1 ) & (y_pred == 1))
	TN = np.sum((y_true == 0 ) & (y_pred == 0))
	FN = np.sum((y_true == 1 ) & (y_pred == 0))
	FP = np.sum((y_true == 0 ) & (y_pred == 1))
	
	Recall = TP / (TP + FN )
	Precision = TP / (TP + FP)
	if (beta**2 * Precision) + Recall == 0:
		return 0.0
	F_Score = ( 1 + beta**2) * ((Precision * Recall) / ((beta**2 * Precision) + Recall) )
	return np.round(F_Score , 3)



y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 0, 0, 1])
beta = 1
print(f_score(y_true, y_pred, beta))

0.857


***Generate a Confusion Matrix for Binary Classification***

In [ ]:
def confusion_matrix(data):
    tp, fn, fp, tn = 0, 0, 0, 0
    for pair in data:
        y_true, y_pred = pair[0], pair[1]
        
        if y_true == 0 and y_pred == 0 :
            tn +=1
        elif y_true == 1 and y_pred == 1 :   
            tp += 1
        elif y_true == 0 and y_pred == 1 :
            fp += 1
        else :
            fn += 1        
    return [[tp , fn] , [fp , tn ]]

data = [[1, 1], [1, 0], [0, 1], [0, 0], [0, 1]]
print(confusion_matrix(data))


[[1, 1], [2, 1]]


In [9]:
import numpy as np 

def confusion_matrix(data):

    arr = np.array(data)
    y_true = arr[:, 0]  # all true labels
    y_pred = arr[:, 1]  # all predicted labels

    TP = np.sum((y_true == 1 ) & (y_pred == 1))
    TN = np.sum((y_true == 0 ) & (y_pred == 0))
    FN = np.sum((y_true == 1 ) & (y_pred == 0))
    FP = np.sum((y_true == 0 ) & (y_pred == 1))

    return [[int(TP), int(FN)], [int(FP), int(TN)]]
	    
data = [[1, 1], [1, 0], [0, 1], [0, 0], [0, 1]]
print(confusion_matrix(data))


[[1, 1], [2, 1]]


***Implement Precision Metric***

In [3]:
import numpy as np
def precision(y_true, y_pred):
	# Your code here
	TP = np.sum((y_true==1) & (y_pred==1))
	FP = np.sum((y_true==0) & (y_pred==1))
	Precision = TP / (TP + FP)
	return Precision


y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 0, 0, 1])
result = precision(y_true, y_pred)
print(result)

1.0


***Implement Recall Metric in Binary Classification***

In [ ]:
import numpy as np

def recall(y_true, y_pred):
    """
    Calculate the recall metric for binary classification.
    
    Args:
        y_true: Array of true binary labels (0 or 1)
        y_pred: Array of predicted binary labels (0 or 1)
    
    Returns:
        Recall value as a float
    """
    # Your code here
    
    TP = np.sum((y_true == 1) & (y_pred == 1))
    FN = np.sum((y_true == 1) & (y_pred == 0))
    Recall = TP / (TP + FN)
    return Recall

y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 0, 0, 1])
print(round(recall(y_true, y_pred), 3))

0.75


***Expected Value and Variance of an n-Sided Die***

In [5]:
import numpy as np 
def dice_statistics(n: int) -> tuple[float, float]:
	"""
	Compute the expected value and variance of a fair n-sided die roll.

	Args:
		n (int): Number of sides of the die

	Returns:
		tuple: (expected_value, variance)
	"""
	# Your code here
	Expected_Value = (n+1) / 2
	Variance = (n**2 - 1) / 12
	return (Expected_Value , Variance)

import random
random.seed(0)
E,V = dice_statistics(6)
print((round(E,4), round(V,4)))

(3.5, 2.9167)


***Implement Ridge Regression Loss Function***

In [1]:
import numpy as np

def ridge_loss(X: np.ndarray, w: np.ndarray, y_true: np.ndarray, alpha: float) -> float:
    loss = np.mean((y_true - X @ w)**2) + alpha * np.sum(w**2)
    return loss

X = np.array([[1,1],[2,1],[3,1],[4,1]])
W = np.array([.2,2])
y = np.array([2,3,4,5])
alpha = 0.1
output = ridge_loss(X, W, y, alpha)
print(output)

2.204


***Sampling Distribution of the Mean***

In [2]:
import numpy as np

def simulate_clt(num_samples: int, sample_size: int, distribution: str = 'uniform') -> float:
    """
    Compute the mean of sample means to demonstrate the sampling distribution.

    Args:
        num_samples: Number of independent samples to draw
        sample_size: Size of each sample
        distribution: 'uniform' (0,1) or 'exponential' (scale=1)

    Returns:
        Mean of the sample means (float)
    """
    # Your code here
    mean_list = []
    for i in range(num_samples):
        if distribution == "uniform":
            sample = np.random.uniform(0, 1, sample_size)
        elif distribution == "exponential":
            sample = np.random.exponential(1, sample_size)
    
        mean_list.append(np.mean(sample))
    return np.mean(mean_list)    
        


np.random.seed(42)
print(round(simulate_clt(1000, 30, 'uniform'), 4))
    

0.4996


***Calculate Performance Metrics for a Classification Model***

In [6]:
import numpy as np 
def performance_metrics(actual: list[int], predicted: list[int]) -> tuple:
	# Implement your code here
	actual = np.array(actual)
	predicted = np.array(predicted)
	TP = np.sum((actual == 1) & (predicted ==1))
	TN = np.sum((actual == 0) & (predicted == 0))
	FP = np.sum((actual == 0) & (predicted == 1))
	FN = np.sum((actual == 1) & (predicted == 0))
	confusion_matrix = [[int(TP) , int(FN)],[int(FP) , int(TN)]]
	accuracy = (TP+TN) / (TP+TN+FP+FN)
	specificity = TN / (TN+FP)
	negativePredictive = TN / (TN+FN)
	Precision = TP / (TP+FP)
	Recall = TP / (TP+FN)
	f1 = (2 * (Precision * Recall)) / (Precision + Recall)
    
	return confusion_matrix, round(float(accuracy), 3), round(float(f1), 3), round(float(specificity), 3), round(float(negativePredictive), 3)

actual = [1, 0, 1, 0, 1]
predicted = [1, 0, 0, 1, 1]
print(performance_metrics(actual, predicted))


([[2, 1], [1, 1]], 0.6, 0.667, 0.5, 0.5)


***Implement ReLU Activation Function***

In [1]:
def relu(z: float) -> float:
	# Your code here
	return float(max(0,z))

print(relu(0)) 
print(relu(1)) 
print(relu(-1))

0.0
1.0
0.0


***Implementation of Log Softmax Function***

In [2]:
import numpy as np

def log_softmax(scores: list) -> np.ndarray:
	# Your code here
	log_softmax_i = scores - np.max(scores) - np.log(np.sum(np.exp(scores - np.max(scores))))
	return log_softmax_i	

print(log_softmax([1, 2, 3]))

[-2.40760596 -1.40760596 -0.40760596]


***Batch Iterator for Dataset***

In [8]:
import numpy as np

def batch_iterator(X, y=None, batch_size=64):
	# Your code here
	n = len(X)
	result = []
	for i in range(0, n, batch_size):
		X_batch = X[i:i+batch_size]
		
		if y is None:
			result.append([X_batch])
		else :
			y_batch = y[i:i+batch_size]
			result.append([X_batch.tolist(),y_batch.tolist()])
	return result
					

print(batch_iterator(np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]), np.array([1, 2, 3, 4, 5]), batch_size=2))

[[[[1, 2], [3, 4]], [1, 2]], [[[5, 6], [7, 8]], [3, 4]], [[[9, 10]], [5]]]


***Sigmoid Activation Function Understanding***

In [1]:
import math

def sigmoid(z: float) -> float:
	#Your code here
	result = 1 / (1 + math.exp(-z))
	return result

print(sigmoid(0))

0.5


***Softmax Activation Function Implementation***

In [14]:
import math
import numpy as np 
def softmax(scores):
    maxx = np.max(scores)       # compute once, using ALL scores
    denom = np.sum([math.exp(z - maxx) for z in scores])       # compute once, using ALL scores
    
    results = []
    for score in scores:
        result = float(math.exp(score - maxx) / denom )   # now use maxx and denom here
        results.append(result)
    return results

print([round(x, 4) for x in softmax([1, 2, 3])])

[0.09, 0.2447, 0.6652]


***Binary Classification with Logistic Regression***

In [7]:
import numpy as np

def predict_logistic(X: np.ndarray, weights: np.ndarray, bias: float) -> np.ndarray:
	"""
	Implements binary classification prediction using Logistic Regression.

	Args:
		X: Input feature matrix (shape: N x D)
		weights: Model weights (shape: D)
		bias: Model bias

	Returns:
		Binary predictions (0 or 1)
	"""
	# Your code here
	z = (X @ weights ) + bias 
	z = np.clip(z, -500, 500)
	
	sigma = 1 / (1 + np.exp(-z))
	return (sigma > 0.5).astype(int)	


print(predict_logistic(np.array([[1, 1], [2, 2], [-1, -1], [-2, -2]]), np.array([1, 1]), 0))

[1 1 0 0]


***Empirical Probability Mass Function (PMF)***

In [14]:
import numpy as np 

def empirical_pmf(samples):
    """
    Given an iterable of integer samples, return a list of (value, probability)
    pairs sorted by value ascending.
    """
    # TODO: Implement the function
    if not samples :
        return []
    n = len(samples)
    values, counts = np.unique(samples, return_counts=True) # return how many time the value is appears 
    prob = counts / n
    return [(int(v), float(p)) for v, p in zip(values, prob)]

print(empirical_pmf([1, 2, 2, 3, 3, 3]))

    

[(1, 0.16666666666666666), (2, 0.3333333333333333), (3, 0.5)]


***Calculate Conditional Probability from Data***

In [17]:
import numpy as np 

def conditional_probability(data, x, y):
    """
    Returns the probability P(Y=y|X=x) from list of (X, Y) pairs.
    Args:
      data: List of (X, Y) tuples
      x: value of X to condition on
      y: value of Y to check
    Returns:
      float: conditional probability, rounded to 4 decimal places
    """
    # Your code here
    x_count = len([1 for (X_val, Y_val) in data if X_val == x])
    y_count = len([1 for (X_val, Y_val) in data if X_val == x and Y_val == y])
    if x_count == 0 :
        return  0.0
    else :
        return (y_count / x_count)
    
data = [('sunny', 'walk'), ('rainy', 'read'), ('sunny', 'run'), ('cloudy', 'read'), ('sunny', 'walk')]
print(conditional_probability(data, 'sunny', 'walk'))    

0.6666666666666666


***Compute Total Probability using Law of Total Probability***

In [2]:
def law_of_total_probability(priors: dict, conditionals: dict) -> float:
    """
    Compute P(A) using the Law of Total Probability.
    
    Args:
        priors: Dictionary mapping partition event names to P(Bi)
        conditionals: Dictionary mapping partition event names to P(A|Bi)
    
    Returns:
        float: The total probability P(A), rounded to 4 decimal places
    """
    # Your code here
    result = 0
    for key  in priors.keys() :
        probofB = priors[key]
        probAofB = conditionals[key]
        result += probofB * probAofB
    return result

priors = {'B1': 0.3, 'B2': 0.7}
conditionals = {'B1': 0.2, 'B2': 0.5}
print(law_of_total_probability(priors, conditionals))    

0.41


***Implement K-Fold Cross-Validation***

In [1]:
import numpy as np
from typing import List, Tuple

def k_fold_cross_validation(n_samples: int, k: int = 5, shuffle: bool = True) -> List[Tuple[List[int], List[int]]]:
    """
    Generate train/test index splits for k-fold cross-validation.
    
    Args:
        n_samples: Total number of samples in the dataset
        k: Number of folds (default 5)
        shuffle: Whether to shuffle indices before splitting (default True)
    
    Returns:
        List of (train_indices, test_indices) tuples
    """
    # Your code here
    indices = np.arange(n_samples) 
    if shuffle :
        np.random.shuffle(indices)
    folds = []
    start = 0
    base_size = n_samples // k
    remainder = n_samples %  k 
    for i in range(k):
        if i < remainder:
            fold_size = base_size + 1
        else:
            fold_size = base_size 
        end = start + fold_size
        folds.append(indices[start:end])
        start = end
    result = []
    for i in range(k):
        test_indices  = folds[i]        # just fold i
        train_indices = np.concatenate([folds[j] for j in range(k) if j != i])         # all other folds combined
        result.append((train_indices, test_indices))
    return result
        
import numpy as np
np.random.seed(42)
print(k_fold_cross_validation(n_samples=10, k=5, shuffle=False))


[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])), (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])), (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])), (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])), (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]


***Single Neuron***

In [1]:
import math
import numpy as np 


def single_neuron_model(features: list[list[float]], labels: list[int], weights: list[float], bias: float) :
	# Your code here
	z=np.dot(features,weights)+bias
	sigma = 1 / (1 + np.exp(-z))
	mse = np.mean((sigma - labels)**2)
	
	return np.round(sigma,4).tolist(), np.round(mse,4).tolist()

print(single_neuron_model([[0.5, 1.0], [-1.5, -2.0], [2.0, 1.5]], [0, 1, 0], [0.7, -0.4], -0.1))

([0.4626, 0.4134, 0.6682], 0.3349)


***Matrix Determinant & Trace***

In [ ]:
import numpy as np 

def matrix_determinant_and_trace(matrix: list[list[float]]) -> tuple[float, float]:
        
        def determinant(matrix):
            if len(matrix) == 1:
                return matrix[0][0] 
            det = 0
            for j in range(len(matrix)):
                minor = [row[:j] + row[j+1:] for row in matrix[1:]]
                det += (-1)**(j) * matrix[0][j] * determinant(minor)
            return det	
        
        the_trace = sum(np.diag(matrix))
        the_det = determinant(matrix)
        return (float(the_det), float(the_trace))
        

In [ ]:
import numpy as np

def matrix_determinant_and_trace(matrix: list[list[float]]) -> tuple[float, float]:
    m = np.array(matrix)
    return (float(np.linalg.det(m)), float(np.trace(m)))