***Create and Inspect a Tensor***

In [2]:
import torch

def make_tensor():
    """Return a 2x3 float32 tensor [[1, 2, 3], [4, 5, 6]]."""
    # TODO
    return torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)

t = make_tensor()
print(t)
print("----------------")
t = make_tensor()
print(tuple(t.shape))
print("----------------")
t = make_tensor()
print(float(t[1, 2].item()))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
----------------
(2, 3)
----------------
6.0


***Reshape and Transpose a Tensor***

In [3]:
import torch

def reshape_transpose(t):
    """Reshape a 1D tensor of 6 elements to 2x3 (row-major) and return its transpose.

    Args:
        t (torch.Tensor): 1D tensor with exactly 6 elements.

    Returns:
        torch.Tensor: Transpose of the 2x3 reshape, with shape (3, 2).
    """
    # TODO: reshape to (2, 3) then transpose to (3, 2)
    return t.reshape(2, 3).T   # or use .t() 

print(reshape_transpose(torch.tensor([1, 2, 3, 4, 5, 6])))
print("---------------------")
print(reshape_transpose(torch.tensor([1., 2., 3., 4., 5., 6.])))


tensor([[1, 4],
        [2, 5],
        [3, 6]])
---------------------
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


***Gradient of a Square with Autograd***

In [ ]:
import torch

def grad_of_square(x_val):
    
    # TODO: create tensor, compute y = x**2, backward, return grad
    x = torch.tensor(x_val, requires_grad=True)
    y = x ** 2
    y.backward()
    return x.grad.item()
  

print(grad_of_square(3.0))